#!/bin/bash

#PBS -P SIHnextgen
#PBS -l select=1:ncpus=1:mem=8gb
#PBS -l walltime=1:00:00
#PBS -N build01

module load singularity

# Assuming you are running this from your project folder, /project/<YOUR_PROJECT>
cd $PBS_O_WORKDIR

# If these are not set, it defaults to your home folder which will fill up very quickly.
export SINGULARITY_CACHEDIR=`pwd`
export SINGULARITY_TMPDIR=`pwd`

# Build takes around 30 mins.
singularity build rstan.img docker://sydneyinformaticshub/rstan:4.0.5
